// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHGhIKj4Ct4F9bzG9UIaRZzCQKhonXwGY',
    appId: '1:233194873646:web:3495b8c1dbe45f5e4dd0bf',
    messagingSenderId: '233194873646',
    projectId: 'uploadfirebase-b49ff',
    authDomain: 'uploadfirebase-b49ff.firebaseapp.com',
    storageBucket: 'uploadfirebase-b49ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnsj5Z-R19UAAWco-xpyk9s80TpQRi3K0',
    appId: '1:233194873646:android:08373f0e26d27ffa4dd0bf',
    messagingSenderId: '233194873646',
    projectId: 'uploadfirebase-b49ff',
    storageBucket: 'uploadfirebase-b49ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpwbE2c56bV_sroHCOrVU3QBqWxNZiN4k',
    appId: '1:233194873646:ios:afba53ce6048f91a4dd0bf',
    messagingSenderId: '233194873646',
    projectId: 'uploadfirebase-b49ff',
    storageBucket: 'uploadfirebase-b49ff.appspot.com',
    iosBundleId: 'com.agrgal.uploadsFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpwbE2c56bV_sroHCOrVU3QBqWxNZiN4k',
    appId: '1:233194873646:ios:afba53ce6048f91a4dd0bf',
    messagingSenderId: '233194873646',
    projectId: 'uploadfirebase-b49ff',
    storageBucket: 'uploadfirebase-b49ff.appspot.com',
    iosBundleId: 'com.agrgal.uploadsFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHGhIKj4Ct4F9bzG9UIaRZzCQKhonXwGY',
    appId: '1:233194873646:web:d4a30c861a18e37f4dd0bf',
    messagingSenderId: '233194873646',
    projectId: 'uploadfirebase-b49ff',
    authDomain: 'uploadfirebase-b49ff.firebaseapp.com',
    storageBucket: 'uploadfirebase-b49ff.appspot.com',
  );

}